// qpu-master/packages/motion-gpu/src/lib/svelte/Portal.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		target?: string | HTMLElement | null;
		children?: Snippet;
	}

	let { target = 'body', children }: Props = $props();

	function resolveTargetElement(input: string | HTMLElement | null | undefined): HTMLElement {
		return typeof input === 'string'
			? (document.querySelector<HTMLElement>(input) ?? document.body)
			: (input ?? document.body);
	}

	const portal = (node: HTMLDivElement) => {
		const targetElement = resolveTargetElement(target);
		targetElement.appendChild(node);

		return () => {
			if (node.parentNode === targetElement) {
				targetElement.removeChild(node);
			}
		};
	};
</script>

<div {@attach portal}>
	{@render children?.()}
</div>

// qpu-master/packages/motion-gpu/src/lib/react/Portal.tsx
import { useEffect, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';

export interface PortalProps {
	target?: string | HTMLElement | null;
	children?: ReactNode;
}

function resolveTargetElement(input: string | HTMLElement | null | undefined): HTMLElement {
	if (typeof document === 'undefined') {
		throw new Error('Portal target resolution requires a browser environment');
	}

	return typeof input === 'string'
		? (document.querySelector<HTMLElement>(input) ?? document.body)
		: (input ?? document.body);
}

export function Portal({ target = 'body', children }: PortalProps) {
	const [targetElement, setTargetElement] = useState<HTMLElement | null>(null);

	useEffect(() => {
		if (typeof document === 'undefined') {
			return;
		}
		setTargetElement(resolveTargetElement(target));
	}, [target]);

	if (!targetElement) {
		return null;
	}

	return createPortal(<div>{children ?? null}</div>, targetElement);
}
